name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * 0' # Runs every Sundat at 00:00 UTC
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch and Update README
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: 'https://www.avonture.be/blog/rss.xml'
          max_post_count: '9'
          comment_tag_name: 'feed'
          date_format: 'yyyy-mm-dd'
          
          template: |
            <table style="width:100%; border:0px solid transparent; margin-bottom: 20px;">
              <tr>
                <td style="width:120px; vertical-align:top; padding-right:15px; border:0px solid transparent;">
                  <a href="$url">
                    <img width="120px" src="$postImage" alt="$title" style="border-radius: 8px;">
                  </a>
                </td>
                <td style="vertical-align:top; border:0px solid transparent;">
                  <a href="$url" style="font-weight: bold; font-size: 1.1em; text-decoration: none;">$title</a>
                  <br>
                  <small style="color: #6a737d;">Publi√© le $date</small>
                  <p style="margin-top: 5px; font-size: 0.9em;">$description...</p>
                </td>
              </tr>
            </table>
          
          commit_message: 'feat: Update README with latest blog posts'